apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: hellowhaledeployment-1
  namespace: jenkins-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hellowhale-1
      spec:
      containers:
      - name: hellowhale-1
      image: gitlab.bss.dev.jio.com:5001/root/sit-project/hellowhale:2.0
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      imagePullSecrets: 
      - name: gitleo-registry-sit