
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: hellowhale-1
  namespace: jenkins-demo
  labels:
    app: hellowhale-1
space:
  type: NodePort
  ports:
  - port: 80
    name: hellowhale-1
    targetPort: 80
  selector:
    app: hellowhale-1
---
